name: Continuos integration
on:
 workflow_call:
  inputs:
    environment:
      type: string
      required: true
    source-folder:
      type: string
      required: true
      
  outputs:
    github-artifact-name:
      value: ${{ jobs.build.outputs.github-artifact-name  }}
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_ARTIFACT_NAME: 'gh-artifact'
      SOURCE_FOLDER: '.'
  outputs:
    github-artifact-name: ${{ env.GITHUB_ARTIFACT_NAME}}

  steps:
    - name: Checkout
      uses: action/checkout@v4

    - name: Publish
      uses: actions/upload-artifact@v4
      with: 
        name: ${{ env.GITHUB_ARTIFACT_NAME }} 
        path: ${{ env.SOURCE_FOLDER }}
        retention-days: 1 

