name: Caller workflow
on:
  workflow_dispatch:
    inputs:
      environment: 
        type: choice
        options:
          - 'DEV'
          - 'HOM'
          - 'PRD'
        default: 'DEV'

jobs:
  call-build:
    uses: ${{ format('{0}/.github/workflows/ci.yaml@develop', github.repository) }}
    with:
      environment: ${{ inputs.environment || inputs.environment.default }}
      source-folder: '/'
