name: Caller workflow
on:
  workflow_dispatch:
    inputs:
      environment: 
        type: choice
        options:
          - 'DEV'
          - 'HOM'
          - 'PRD'
        default: 'DEV'

jobs:
  call-build:
  uses: ${{github.workspace }}/.github/workflows/ci.yaml@develop
  with:
    environment: ${{ inputs.environment || inputs.environment.default }}
    source-folder: '/'
