name: Caller workflow
on:
  workflow_dispatch:
    inputs:
      environment: 
        type: choice
        options:
          - 'DEV'
          - 'HOM'
          - 'PRD'
        default: 'DEV'
      purge_cdn:
        type: boolean
        default: false

jobs:
  call-build:
    uses: 'gha-learning/stattic-website/.github/workflows/ci.yaml@develop' 
    with:
      environment: ${{ inputs.environment }}
      source-folder: 'src'
    secrets: inherit
  call-deploy:
    needs: ['call-build']
    uses: 'gha-learning/stattic-website/.github/workflows/cd.yaml@develop'
    with:
      artifact-name: ${{ needs.call-build.outputs.github-artifact-name}}
      environment: ${{ inputs.environment}}
      purge_cdn: ${{ inputs.purge_cdn }}
    secrets: inherit
