name: Caller workflow
on:
  workflow_dispatch:
    inputs:
      environment: 
        type: choice
        options:
          - 'DEV'
          - 'HOM'
          - 'PRD'
        default: 'DEV'

jobs:
  call-build:
    uses: 'gha-learning/stattic-website/.github/workflows/ci.yaml@develop' 
    with:
      environment: ${{ inputs.environment }}
      source-folder: 'src'
