name: Continuos deployment

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        default: 'DEV'
      artifact-name:
        type: string
        required: true
      destination_container:
        type: string
        required: true
      purge_cdn:
        type: boolean
        default: false


jobs:
  deploy:
    environment: ${inputs.environment}
    runs-on: ubuntu-latest
    env:
      TARGET: ${{github.workspace}}/target
    
    steps:

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{inputs.artifact-name }}
        path: 'target'

    
    # - name: Azure login
    #   uses: azure/login@v2
    #   with:
    #     creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    - name: Login
      run: |
        az login --service-principal \
        --username ${{ secrets.AZURE_CLIENT_ID }} \
        --password ${{ secrets.AZURE_CLIENT_SECRET }} \
        --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Set subscription
      run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}


    - name: Upload to blob storage
      run: |
        az storage blob upload-batch --destination ${{ inputs.destination_container }} --source target/ --account-name ${{ vars.STORAGE_ACCOUNT_NAME }}
    
    - name: Pruge CDN endpoint
      if: ${{inputs.purge_cdn}}
      uses: azure/cli@v2
      with:
        inlinescript: |
          az cdn endpoint purge --content-paths "/*" --profile-name "CDN_PROFILE_NAME" \
          --name "CDN_ENDPOINT" --resource-group "RESOURCE_GROUP"
    
    - name: logout
      if: always()
      run: |
        az logout
    