name: Continuos integration
on:
 workflow_call:
  inputs:
    environment:
      type: string
      required: true
    source-folder:
      type: string
      required: true
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      github-artifact-id: ${{ steps.upload-artifact.outputs.artifact-id}}

    steps:
      - name: Checkout
        uses: action/checkout@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        id: upload-artifact
        with: 
          path: ${{ inputs.source-folder }}
          retention-days: 1 

